apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://gitlab.sas.com/convoy/devops/k8s-bases.git/bases/deployment/spring-23?ref=release-3.3
- https://gitlab.sas.com/convoy/devops/k8s-bases.git/bases/service?ref=release-3.3
- https://gitlab.sas.com/convoy/devops/k8s-bases.git/bases/networking.k8s.io/v1/ingress/nginx/rewrite?ref=release-3.3
- https://gitlab.sas.com/convoy/devops/k8s-bases.git/bases/projectcontour.io/v1/httpproxy/base?ref=release-3.3
- https://gitlab.sas.com/convoy/devops/k8s-bases.git/bases/route.openshift.io/v1/route/base?ref=release-3.3
- https://gitlab.sas.com/convoy/devops/k8s-bases.git/bases/istio/virtual-service?ref=release-3.3
- https://gitlab.sas.com/convoy/devops/k8s-bases.git/bases/istio/destination-rule?ref=release-3.3
- https://gitlab.sas.com/convoy/devops/k8s-bases.git/bases/autoscaling/v2/horizontalpodautoscaler/deployment/spring?ref=release-3.3
- https://gitlab.sas.com/convoy/devops/k8s-bases.git/bases/policy/v1/poddisruptionbudget/base?ref=release-3.3
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: $(SAS_SERVICE_NAME)-parameters
  envs:
  - params.env
images:
- name: duname
  newName: $(SAS_DU_NAME)
vars:
- name: SAS_SERVICE_NAME
  objref:
    kind: ConfigMap
    name: $(SAS_SERVICE_NAME)-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.SAS_SERVICE_NAME
- name: SAS_DU_NAME
  objref:
    kind: ConfigMap
    name: $(SAS_SERVICE_NAME)-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.SAS_DU_NAME
- name: SAS_CONTEXT_PATH
  objref:
    kind: ConfigMap
    name: $(SAS_SERVICE_NAME)-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.SAS_CONTEXT_PATH
