/*
Copyright © 2023, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
SPDX-License-Identifier: Apache-2.0
*/
/*
 * Decisions
 * The Decisions API supports the life cycle of decision data.
 *
 * OpenAPI spec version: 7
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sas.rtdm2id.model.id.decision;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Analysis Code generated by a Score Object using Score Execution. This represents application/vnd.sas.score.analysis.code media type (version 1).
 */
@ApiModel(description = "Analysis Code generated by a Score Object using Score Execution. This represents application/vnd.sas.score.analysis.code media type (version 1).")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-06T21:19:27.553+03:00")


public class AnalysisCode {
  @JsonProperty("code")
  private String code = null;

  @JsonProperty("codeType")
  private String codeType = null;

  @JsonProperty("outputTableName")
  private String outputTableName = null;

  @JsonProperty("outputLibraryName")
  private String outputLibraryName = null;

  @JsonProperty("analysisType")
  private String analysisType = null;

  @JsonProperty("version")
  private Integer version = null;

  public AnalysisCode code(String code) {
    this.code = code;
    return this;
  }

  /**
   * Executable code generated by a Score Object.
   *
   * @return code
   **/
  @ApiModelProperty(required = true, value = "Executable code generated by a Score Object.")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public AnalysisCode codeType(String codeType) {
    this.codeType = codeType;
    return this;
  }

  /**
   * Type of the code.
   *
   * @return codeType
   **/
  @ApiModelProperty(required = true, value = "Type of the code.")
  public String getCodeType() {
    return codeType;
  }

  public void setCodeType(String codeType) {
    this.codeType = codeType;
  }

  public AnalysisCode outputTableName(String outputTableName) {
    this.outputTableName = outputTableName;
    return this;
  }

  /**
   * Name of the table that will be generated when the generated code is executed.
   *
   * @return outputTableName
   **/
  @ApiModelProperty(required = true, value = "Name of the table that will be generated when the generated code is executed.")
  public String getOutputTableName() {
    return outputTableName;
  }

  public void setOutputTableName(String outputTableName) {
    this.outputTableName = outputTableName;
  }

  public AnalysisCode outputLibraryName(String outputLibraryName) {
    this.outputLibraryName = outputLibraryName;
    return this;
  }

  /**
   * Name of the library where the table will be generated when the code is executed.
   *
   * @return outputLibraryName
   **/
  @ApiModelProperty(required = true, value = "Name of the library where the table will be generated when the code is executed.")
  public String getOutputLibraryName() {
    return outputLibraryName;
  }

  public void setOutputLibraryName(String outputLibraryName) {
    this.outputLibraryName = outputLibraryName;
  }

  public AnalysisCode analysisType(String analysisType) {
    this.analysisType = analysisType;
    return this;
  }

  /**
   * Type of analysis which the code will perform.
   *
   * @return analysisType
   **/
  @ApiModelProperty(required = true, value = "Type of analysis which the code will perform.")
  public String getAnalysisType() {
    return analysisType;
  }

  public void setAnalysisType(String analysisType) {
    this.analysisType = analysisType;
  }

  public AnalysisCode version(Integer version) {
    this.version = version;
    return this;
  }

  /**
   * This media type&#39;s schema version number. This representation is version 1.
   *
   * @return version
   **/
  @ApiModelProperty(value = "This media type's schema version number. This representation is version 1.")
  public Integer getVersion() {
    return version;
  }

  public void setVersion(Integer version) {
    this.version = version;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AnalysisCode analysisCode = (AnalysisCode) o;
    return Objects.equals(this.code, analysisCode.code) &&
            Objects.equals(this.codeType, analysisCode.codeType) &&
            Objects.equals(this.outputTableName, analysisCode.outputTableName) &&
            Objects.equals(this.outputLibraryName, analysisCode.outputLibraryName) &&
            Objects.equals(this.analysisType, analysisCode.analysisType) &&
            Objects.equals(this.version, analysisCode.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, codeType, outputTableName, outputLibraryName, analysisType, version);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AnalysisCode {\n");

    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    codeType: ").append(toIndentedString(codeType)).append("\n");
    sb.append("    outputTableName: ").append(toIndentedString(outputTableName)).append("\n");
    sb.append("    outputLibraryName: ").append(toIndentedString(outputLibraryName)).append("\n");
    sb.append("    analysisType: ").append(toIndentedString(analysisType)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

