/*
Copyright © 2023, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
SPDX-License-Identifier: Apache-2.0
*/
/*
 * Decisions
 * The Decisions API supports the life cycle of decision data.
 *
 * OpenAPI spec version: 7
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sas.rtdm2id.model.id.decision;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Represents the code file signature term.
 */
@ApiModel(description = "Represents the code file signature term.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-06T21:19:27.553+03:00")


public class CodeFileSignatureTerm {
  @JsonProperty("name")
  private String name = null;

  /**
   * Data type of the code file signature term.
   */
  public enum DataTypeEnum {
    STRING("string"),

    DECIMAL("decimal"),

    INTEGER("integer"),

    DATAGRID("dataGrid"),

    DATE("date"),

    DATETIME("datetime"),

    UNKNOWN("unknown");

    private String value;

    DataTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DataTypeEnum fromValue(String text) {
      for (DataTypeEnum b : DataTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("dataType")
  private DataTypeEnum dataType = null;

  /**
   * Direction of the code file signature term.
   */
  public enum DirectionEnum {
    INPUT("input"),

    INOUT("inOut");

    private String value;

    DirectionEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DirectionEnum fromValue(String text) {
      for (DirectionEnum b : DirectionEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("direction")
  private DirectionEnum direction = null;

  @JsonProperty("length")
  private Integer length = null;

  @JsonProperty("dataGridExtension")
  private List<CodeFileSignatureTermDataGridExtension> dataGridExtension = null;

  public CodeFileSignatureTerm name(String name) {
    this.name = name;
    return this;
  }

  /**
   * The name of the code file signature term.
   *
   * @return name
   **/
  @ApiModelProperty(required = true, value = "The name of the code file signature term.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CodeFileSignatureTerm dataType(DataTypeEnum dataType) {
    this.dataType = dataType;
    return this;
  }

  /**
   * Data type of the code file signature term.
   *
   * @return dataType
   **/
  @ApiModelProperty(required = true, value = "Data type of the code file signature term.")
  public DataTypeEnum getDataType() {
    return dataType;
  }

  public void setDataType(DataTypeEnum dataType) {
    this.dataType = dataType;
  }

  public CodeFileSignatureTerm direction(DirectionEnum direction) {
    this.direction = direction;
    return this;
  }

  /**
   * Direction of the code file signature term.
   *
   * @return direction
   **/
  @ApiModelProperty(required = true, value = "Direction of the code file signature term.")
  public DirectionEnum getDirection() {
    return direction;
  }

  public void setDirection(DirectionEnum direction) {
    this.direction = direction;
  }

  public CodeFileSignatureTerm length(Integer length) {
    this.length = length;
    return this;
  }

  /**
   * Length of the signature term. Valid for string data type.
   *
   * @return length
   **/
  @ApiModelProperty(value = "Length of the signature term. Valid for string data type.")
  public Integer getLength() {
    return length;
  }

  public void setLength(Integer length) {
    this.length = length;
  }

  public CodeFileSignatureTerm dataGridExtension(List<CodeFileSignatureTermDataGridExtension> dataGridExtension) {
    this.dataGridExtension = dataGridExtension;
    return this;
  }

  public CodeFileSignatureTerm addDataGridExtensionItem(CodeFileSignatureTermDataGridExtension dataGridExtensionItem) {
    if (this.dataGridExtension == null) {
      this.dataGridExtension = new ArrayList<>();
    }
    this.dataGridExtension.add(dataGridExtensionItem);
    return this;
  }

  /**
   * Metadata information about data grid columns.
   *
   * @return dataGridExtension
   **/
  @ApiModelProperty(value = "Metadata information about data grid columns.")
  public List<CodeFileSignatureTermDataGridExtension> getDataGridExtension() {
    return dataGridExtension;
  }

  public void setDataGridExtension(List<CodeFileSignatureTermDataGridExtension> dataGridExtension) {
    this.dataGridExtension = dataGridExtension;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CodeFileSignatureTerm codeFileSignatureTerm = (CodeFileSignatureTerm) o;
    return Objects.equals(this.name, codeFileSignatureTerm.name) &&
            Objects.equals(this.dataType, codeFileSignatureTerm.dataType) &&
            Objects.equals(this.direction, codeFileSignatureTerm.direction) &&
            Objects.equals(this.length, codeFileSignatureTerm.length) &&
            Objects.equals(this.dataGridExtension, codeFileSignatureTerm.dataGridExtension);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, dataType, direction, length, dataGridExtension);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CodeFileSignatureTerm {\n");

    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    dataType: ").append(toIndentedString(dataType)).append("\n");
    sb.append("    direction: ").append(toIndentedString(direction)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("    dataGridExtension: ").append(toIndentedString(dataGridExtension)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

