/*
Copyright © 2023, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
SPDX-License-Identifier: Apache-2.0
*/
/*
 * Decisions
 * The Decisions API supports the life cycle of decision data.
 *
 * OpenAPI spec version: 7
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sas.rtdm2id.model.id.decision;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Decision Step Code Signature Term DataGrid Extension is used to store the column information of a DataGrid variable.
 */
@ApiModel(description = "Decision Step Code Signature Term DataGrid Extension is used to store the column information of a DataGrid variable.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-06T21:19:27.553+03:00")


public class DecisionStepCodeSignatureTermDataGridExtension {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("length")
  private Integer length = null;

  /**
   * Data type of the dataGrid column.
   */
  public enum DataTypeEnum {
    STRING("string"),

    DECIMAL("decimal"),

    INTEGER("integer"),

    DATE("date"),

    DATETIME("datetime");

    private String value;

    DataTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DataTypeEnum fromValue(String text) {
      for (DataTypeEnum b : DataTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("dataType")
  private DataTypeEnum dataType = null;

  public DecisionStepCodeSignatureTermDataGridExtension name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Name of the dataGrid column.
   *
   * @return name
   **/
  @ApiModelProperty(required = true, value = "Name of the dataGrid column.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public DecisionStepCodeSignatureTermDataGridExtension length(Integer length) {
    this.length = length;
    return this;
  }

  /**
   * Length of the value in the dataGrid column. Valid for dataType string.
   *
   * @return length
   **/
  @ApiModelProperty(value = "Length of the value in the dataGrid column. Valid for dataType string.")
  public Integer getLength() {
    return length;
  }

  public void setLength(Integer length) {
    this.length = length;
  }

  public DecisionStepCodeSignatureTermDataGridExtension dataType(DataTypeEnum dataType) {
    this.dataType = dataType;
    return this;
  }

  /**
   * Data type of the dataGrid column.
   *
   * @return dataType
   **/
  @ApiModelProperty(required = true, value = "Data type of the dataGrid column.")
  public DataTypeEnum getDataType() {
    return dataType;
  }

  public void setDataType(DataTypeEnum dataType) {
    this.dataType = dataType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DecisionStepCodeSignatureTermDataGridExtension decisionStepCodeSignatureTermDataGridExtension = (DecisionStepCodeSignatureTermDataGridExtension) o;
    return Objects.equals(this.name, decisionStepCodeSignatureTermDataGridExtension.name) &&
            Objects.equals(this.length, decisionStepCodeSignatureTermDataGridExtension.length) &&
            Objects.equals(this.dataType, decisionStepCodeSignatureTermDataGridExtension.dataType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, length, dataType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DecisionStepCodeSignatureTermDataGridExtension {\n");

    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("    dataType: ").append(toIndentedString(dataType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

