/*
Copyright © 2023, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
SPDX-License-Identifier: Apache-2.0
*/
/*
 * Decisions
 * The Decisions API supports the life cycle of decision data.
 *
 * OpenAPI spec version: 7
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sas.rtdm2id.model.id.decision;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Executable code generated by a score object using a score definition and input data. This represents application/vnd.sas.score.mapped.code media type (version 1).
 */
@ApiModel(description = "Executable code generated by a score object using a score definition and input data. This represents application/vnd.sas.score.mapped.code media type (version 1).")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-06T21:19:27.553+03:00")


public class MappedCode {
  @JsonProperty("code")
  private String code = null;

  @JsonProperty("codeType")
  private String codeType = null;

  @JsonProperty("outputTableName")
  private String outputTableName = null;

  @JsonProperty("outputLibraryName")
  private String outputLibraryName = null;

  @JsonProperty("version")
  private Integer version = null;

  public MappedCode code(String code) {
    this.code = code;
    return this;
  }

  /**
   * The executable code generated by a score object.
   *
   * @return code
   **/
  @ApiModelProperty(required = true, value = "The executable code generated by a score object.")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public MappedCode codeType(String codeType) {
    this.codeType = codeType;
    return this;
  }

  /**
   * The type of code.
   *
   * @return codeType
   **/
  @ApiModelProperty(required = true, value = "The type of code.")
  public String getCodeType() {
    return codeType;
  }

  public void setCodeType(String codeType) {
    this.codeType = codeType;
  }

  public MappedCode outputTableName(String outputTableName) {
    this.outputTableName = outputTableName;
    return this;
  }

  /**
   * The name of the table that is generated when the code is executed.
   *
   * @return outputTableName
   **/
  @ApiModelProperty(required = true, value = "The name of the table that is generated when the code is executed.")
  public String getOutputTableName() {
    return outputTableName;
  }

  public void setOutputTableName(String outputTableName) {
    this.outputTableName = outputTableName;
  }

  public MappedCode outputLibraryName(String outputLibraryName) {
    this.outputLibraryName = outputLibraryName;
    return this;
  }

  /**
   * The name of the library where the table is generated when the code is executed.
   *
   * @return outputLibraryName
   **/
  @ApiModelProperty(required = true, value = "The name of the library where the table is generated when the code is executed.")
  public String getOutputLibraryName() {
    return outputLibraryName;
  }

  public void setOutputLibraryName(String outputLibraryName) {
    this.outputLibraryName = outputLibraryName;
  }

  public MappedCode version(Integer version) {
    this.version = version;
    return this;
  }

  /**
   * This media type&#39;s schema version number. This representation is version 1.
   *
   * @return version
   **/
  @ApiModelProperty(value = "This media type's schema version number. This representation is version 1.")
  public Integer getVersion() {
    return version;
  }

  public void setVersion(Integer version) {
    this.version = version;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MappedCode mappedCode = (MappedCode) o;
    return Objects.equals(this.code, mappedCode.code) &&
            Objects.equals(this.codeType, mappedCode.codeType) &&
            Objects.equals(this.outputTableName, mappedCode.outputTableName) &&
            Objects.equals(this.outputLibraryName, mappedCode.outputLibraryName) &&
            Objects.equals(this.version, mappedCode.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, codeType, outputTableName, outputLibraryName, version);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MappedCode {\n");

    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    codeType: ").append(toIndentedString(codeType)).append("\n");
    sb.append("    outputTableName: ").append(toIndentedString(outputTableName)).append("\n");
    sb.append("    outputLibraryName: ").append(toIndentedString(outputLibraryName)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

