/*
Copyright © 2023, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
SPDX-License-Identifier: Apache-2.0
*/
/*
 * Decisions
 * The Decisions API supports the life cycle of decision data.
 *
 * OpenAPI spec version: 7
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sas.rtdm2id.model.id.decision;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

/**
 * Provides the base summary information of any object. This represents application/vnd.sas.summary media type (version 1).
 */
@ApiModel(description = "Provides the base summary information of any object. This represents application/vnd.sas.summary media type (version 1).")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-06T21:19:27.553+03:00")


public class ResourceSummary {
  @JsonProperty("id")
  private UUID id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("createdBy")
  private String createdBy = null;

  @JsonProperty("creationTimeStamp")
  private OffsetDateTime creationTimeStamp = null;

  @JsonProperty("modifiedBy")
  private String modifiedBy = null;

  @JsonProperty("modifiedTimeStamp")
  private OffsetDateTime modifiedTimeStamp = null;

  @JsonProperty("links")
  private List<Link> links = null;

  @JsonProperty("version")
  private Integer version = null;

  public ResourceSummary id(UUID id) {
    this.id = id;
    return this;
  }

  /**
   * unique identifier of the object
   *
   * @return id
   **/
  @ApiModelProperty(required = true, value = "unique identifier of the object")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public ResourceSummary name(String name) {
    this.name = name;
    return this;
  }

  /**
   * name of the object
   *
   * @return name
   **/
  @ApiModelProperty(required = true, value = "name of the object")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ResourceSummary type(String type) {
    this.type = type;
    return this;
  }

  /**
   * The type name for this object.
   *
   * @return type
   **/
  @ApiModelProperty(required = true, value = "The type name for this object.")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public ResourceSummary description(String description) {
    this.description = description;
    return this;
  }

  /**
   * description of the object
   *
   * @return description
   **/
  @ApiModelProperty(value = "description of the object")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ResourceSummary createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

  /**
   * user responsible for creating the object
   *
   * @return createdBy
   **/
  @ApiModelProperty(value = "user responsible for creating the object")
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public ResourceSummary creationTimeStamp(OffsetDateTime creationTimeStamp) {
    this.creationTimeStamp = creationTimeStamp;
    return this;
  }

  /**
   * DateTime of object creation
   *
   * @return creationTimeStamp
   **/
  @ApiModelProperty(value = "DateTime of object creation")
  public OffsetDateTime getCreationTimeStamp() {
    return creationTimeStamp;
  }

  public void setCreationTimeStamp(OffsetDateTime creationTimeStamp) {
    this.creationTimeStamp = creationTimeStamp;
  }

  public ResourceSummary modifiedBy(String modifiedBy) {
    this.modifiedBy = modifiedBy;
    return this;
  }

  /**
   * user responsible for most recent modification of the object
   *
   * @return modifiedBy
   **/
  @ApiModelProperty(value = "user responsible for most recent modification of the object")
  public String getModifiedBy() {
    return modifiedBy;
  }

  public void setModifiedBy(String modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  public ResourceSummary modifiedTimeStamp(OffsetDateTime modifiedTimeStamp) {
    this.modifiedTimeStamp = modifiedTimeStamp;
    return this;
  }

  /**
   * DateTime of last object modification
   *
   * @return modifiedTimeStamp
   **/
  @ApiModelProperty(value = "DateTime of last object modification")
  public OffsetDateTime getModifiedTimeStamp() {
    return modifiedTimeStamp;
  }

  public void setModifiedTimeStamp(OffsetDateTime modifiedTimeStamp) {
    this.modifiedTimeStamp = modifiedTimeStamp;
  }

  public ResourceSummary links(List<Link> links) {
    this.links = links;
    return this;
  }

  public ResourceSummary addLinksItem(Link linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<>();
    }
    this.links.add(linksItem);
    return this;
  }

  /**
   * Paging links that apply to this object
   *
   * @return links
   **/
  @ApiModelProperty(value = "Paging links that apply to this object")
  public List<Link> getLinks() {
    return links;
  }

  public void setLinks(List<Link> links) {
    this.links = links;
  }

  public ResourceSummary version(Integer version) {
    this.version = version;
    return this;
  }

  /**
   * This media type&#39;s schema version number. This representation is version 1.
   *
   * @return version
   **/
  @ApiModelProperty(value = "This media type's schema version number. This representation is version 1.")
  public Integer getVersion() {
    return version;
  }

  public void setVersion(Integer version) {
    this.version = version;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResourceSummary resourceSummary = (ResourceSummary) o;
    return Objects.equals(this.id, resourceSummary.id) &&
            Objects.equals(this.name, resourceSummary.name) &&
            Objects.equals(this.type, resourceSummary.type) &&
            Objects.equals(this.description, resourceSummary.description) &&
            Objects.equals(this.createdBy, resourceSummary.createdBy) &&
            Objects.equals(this.creationTimeStamp, resourceSummary.creationTimeStamp) &&
            Objects.equals(this.modifiedBy, resourceSummary.modifiedBy) &&
            Objects.equals(this.modifiedTimeStamp, resourceSummary.modifiedTimeStamp) &&
            Objects.equals(this.links, resourceSummary.links) &&
            Objects.equals(this.version, resourceSummary.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, type, description, createdBy, creationTimeStamp, modifiedBy, modifiedTimeStamp, links, version);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResourceSummary {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    creationTimeStamp: ").append(toIndentedString(creationTimeStamp)).append("\n");
    sb.append("    modifiedBy: ").append(toIndentedString(modifiedBy)).append("\n");
    sb.append("    modifiedTimeStamp: ").append(toIndentedString(modifiedTimeStamp)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

