/*
Copyright © 2023, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
SPDX-License-Identifier: Apache-2.0
*/
/*
 * Decisions
 * The Decisions API supports the life cycle of decision data.
 *
 * OpenAPI spec version: 7
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sas.rtdm2id.model.id.decision;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * A reference to a signature term.
 */
@ApiModel(description = "A reference to a signature term.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-06T21:19:27.553+03:00")


public class SignatureTermReference {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("name")
  private String name = null;

  public SignatureTermReference id(String id) {
    this.id = id;
    return this;
  }

  /**
   * The id for the signature term. This will be populated by the system if not provided.
   *
   * @return id
   **/
  @ApiModelProperty(value = "The id for the signature term. This will be populated by the system if not provided.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public SignatureTermReference name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Name of the term that is being referenced within the objects signature.
   *
   * @return name
   **/
  @ApiModelProperty(required = true, value = "Name of the term that is being referenced within the objects signature.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignatureTermReference signatureTermReference = (SignatureTermReference) o;
    return Objects.equals(this.id, signatureTermReference.id) &&
            Objects.equals(this.name, signatureTermReference.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureTermReference {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

