/*
Copyright © 2023, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
SPDX-License-Identifier: Apache-2.0
*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.05 at 11:21:15 PM MSK 
//


package com.sas.rtdm2id.model.rtdm;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.sas.generated.rtdm.xsd.decision package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BatchLogicalUnitProcessNodeDataDOProcessInputVariableListIBVariableDO_QNAME = new QName("", "IBVariableDO");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sas.generated.rtdm.xsd.decision
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Batch }
     */
    public Batch createBatch() {
        return new Batch();
    }

    /**
     * Create an instance of {@link Batch.LogicalUnit }
     */
    public Batch.LogicalUnit createBatchLogicalUnit() {
        return new Batch.LogicalUnit();
    }

    /**
     * Create an instance of {@link ProcessNodeDataDO }
     */
    public ProcessNodeDataDO createBatchLogicalUnitProcessNodeDataDO() {
        return new ProcessNodeDataDO();
    }

    /**
     * Create an instance of {@link ProcessNodeDataDO.Process }
     */
    public ProcessNodeDataDO.Process createBatchLogicalUnitProcessNodeDataDOProcess() {
        return new ProcessNodeDataDO.Process();
    }

    /**
     * Create an instance of {@link ProcessNodeDataDO.Process.OutputVariableList }
     */
    public ProcessNodeDataDO.Process.OutputVariableList createBatchLogicalUnitProcessNodeDataDOProcessOutputVariableList() {
        return new ProcessNodeDataDO.Process.OutputVariableList();
    }

    /**
     * Create an instance of {@link ProcessNodeDataDO.Process.OutputVariableList.IBVariableDO }
     */
    public ProcessNodeDataDO.Process.OutputVariableList.IBVariableDO createBatchLogicalUnitProcessNodeDataDOProcessOutputVariableListIBVariableDO() {
        return new ProcessNodeDataDO.Process.OutputVariableList.IBVariableDO();
    }

    /**
     * Create an instance of {@link ProcessNodeDataDO.Process.InputVariableList }
     */
    public ProcessNodeDataDO.Process.InputVariableList createBatchLogicalUnitProcessNodeDataDOProcessInputVariableList() {
        return new ProcessNodeDataDO.Process.InputVariableList();
    }

    /**
     * Create an instance of {@link ProcessNodeDataDO.Process.InputVariableList.IBVariableDO }
     */
    public ProcessNodeDataDO.Process.InputVariableList.IBVariableDO createBatchLogicalUnitProcessNodeDataDOProcessInputVariableListIBVariableDO() {
        return new ProcessNodeDataDO.Process.InputVariableList.IBVariableDO();
    }

    /**
     * Create an instance of {@link ProcessNodeDataDO.Process.InputVariableList.IBVariableDO.Value }
     */
    public ProcessNodeDataDO.Process.InputVariableList.IBVariableDO.Value createBatchLogicalUnitProcessNodeDataDOProcessInputVariableListIBVariableDOValue() {
        return new ProcessNodeDataDO.Process.InputVariableList.IBVariableDO.Value();
    }

    /**
     * Create an instance of {@link ProcessNodeDataDO.Process.InputVariableList.IBVariableDO.Identifier }
     */
    public ProcessNodeDataDO.Process.InputVariableList.IBVariableDO.Identifier createBatchLogicalUnitProcessNodeDataDOProcessInputVariableListIBVariableDOIdentifier() {
        return new ProcessNodeDataDO.Process.InputVariableList.IBVariableDO.Identifier();
    }

    /**
     * Create an instance of {@link ProcessNodeDataDO.Process.DatagridIdentifier }
     */
    public ProcessNodeDataDO.Process.DatagridIdentifier createBatchLogicalUnitProcessNodeDataDOProcessDatagridIdentifier() {
        return new ProcessNodeDataDO.Process.DatagridIdentifier();
    }

    /**
     * Create an instance of {@link CellNodeDataDO }
     */
    public CellNodeDataDO createBatchLogicalUnitCellNodeDataDO() {
        return new CellNodeDataDO();
    }

    /**
     * Create an instance of {@link SplitNodeDataDO }
     */
    public SplitNodeDataDO createBatchLogicalUnitSplitNodeDataDO() {
        return new SplitNodeDataDO();
    }

    /**
     * Create an instance of {@link SplitNodeDataDO.SplitOnNodeDataDO }
     */
    public SplitNodeDataDO.SplitOnNodeDataDO createBatchLogicalUnitSplitNodeDataDOSplitOnNodeDataDO() {
        return new SplitNodeDataDO.SplitOnNodeDataDO();
    }

    /**
     * Create an instance of {@link SplitNodeDataDO.SplitOnNodeDataDO.LineItems }
     */
    public SplitNodeDataDO.SplitOnNodeDataDO.LineItems createBatchLogicalUnitSplitNodeDataDOSplitOnNodeDataDOLineItems() {
        return new SplitNodeDataDO.SplitOnNodeDataDO.LineItems();
    }

    /**
     * Create an instance of {@link SplitNodeDataDO.LineItems }
     */
    public SplitNodeDataDO.LineItems createBatchLogicalUnitSplitNodeDataDOLineItems() {
        return new SplitNodeDataDO.LineItems();
    }

    /**
     * Create an instance of {@link SplitNodeDataDO.LineItems.SplitNodeLineItemDO }
     */
    public SplitNodeDataDO.LineItems.SplitNodeLineItemDO createBatchLogicalUnitSplitNodeDataDOLineItemsSplitNodeLineItemDO() {
        return new SplitNodeDataDO.LineItems.SplitNodeLineItemDO();
    }

    /**
     * Create an instance of {@link ReplyNodeDataDO }
     */
    public ReplyNodeDataDO createBatchLogicalUnitReplyNodeDataDO() {
        return new ReplyNodeDataDO();
    }

    /**
     * Create an instance of {@link ReplyNodeDataDO.EventReply }
     */
    public ReplyNodeDataDO.EventReply createBatchLogicalUnitReplyNodeDataDOEventReply() {
        return new ReplyNodeDataDO.EventReply();
    }

    /**
     * Create an instance of {@link ReplyNodeDataDO.EventReply.ReplyVars }
     */
    public ReplyNodeDataDO.EventReply.ReplyVars createBatchLogicalUnitReplyNodeDataDOEventReplyReplyVars() {
        return new ReplyNodeDataDO.EventReply.ReplyVars();
    }

    /**
     * Create an instance of {@link ReplyNodeDataDO.EventReply.ReplyVars.IBVariableDO }
     */
    public ReplyNodeDataDO.EventReply.ReplyVars.IBVariableDO createBatchLogicalUnitReplyNodeDataDOEventReplyReplyVarsIBVariableDO() {
        return new ReplyNodeDataDO.EventReply.ReplyVars.IBVariableDO();
    }

    /**
     * Create an instance of {@link ReplyNodeDataDO.EventReply.ReplyVars.IBVariableDO.Value }
     */
    public ReplyNodeDataDO.EventReply.ReplyVars.IBVariableDO.Value createBatchLogicalUnitReplyNodeDataDOEventReplyReplyVarsIBVariableDOValue() {
        return new ReplyNodeDataDO.EventReply.ReplyVars.IBVariableDO.Value();
    }

    /**
     * Create an instance of {@link ReplyNodeDataDO.EventReply.ReplyVars.IBVariableDO.ErrorValue }
     */
    public ReplyNodeDataDO.EventReply.ReplyVars.IBVariableDO.ErrorValue createBatchLogicalUnitReplyNodeDataDOEventReplyReplyVarsIBVariableDOErrorValue() {
        return new ReplyNodeDataDO.EventReply.ReplyVars.IBVariableDO.ErrorValue();
    }

    /**
     * Create an instance of {@link ReplyNodeDataDO.Definition }
     */
    public ReplyNodeDataDO.Definition createBatchLogicalUnitReplyNodeDataDODefinition() {
        return new ReplyNodeDataDO.Definition();
    }

    /**
     * Create an instance of {@link ReplyNodeDataDO.ContactHistoryVariables }
     */
    public ReplyNodeDataDO.ContactHistoryVariables createBatchLogicalUnitReplyNodeDataDOContactHistoryVariables() {
        return new ReplyNodeDataDO.ContactHistoryVariables();
    }

    /**
     * Create an instance of {@link ReplyNodeDataDO.ContactHistoryVariables.IBVariableDO }
     */
    public ReplyNodeDataDO.ContactHistoryVariables.IBVariableDO createBatchLogicalUnitReplyNodeDataDOContactHistoryVariablesIBVariableDO() {
        return new ReplyNodeDataDO.ContactHistoryVariables.IBVariableDO();
    }

    /**
     * Create an instance of {@link ReplyNodeDataDO.AudienceList }
     */
    public ReplyNodeDataDO.AudienceList createBatchLogicalUnitReplyNodeDataDOAudienceList() {
        return new ReplyNodeDataDO.AudienceList();
    }

    /**
     * Create an instance of {@link ReplyNodeDataDO.AudienceList.AudienceDO }
     */
    public ReplyNodeDataDO.AudienceList.AudienceDO createBatchLogicalUnitReplyNodeDataDOAudienceListAudienceDO() {
        return new ReplyNodeDataDO.AudienceList.AudienceDO();
    }

    /**
     * Create an instance of {@link StartNodeDataDO }
     */
    public StartNodeDataDO createBatchLogicalUnitStartNodeDataDO() {
        return new StartNodeDataDO();
    }

    /**
     * Create an instance of {@link StartNodeDataDO.Event }
     */
    public StartNodeDataDO.Event createBatchLogicalUnitStartNodeDataDOEvent() {
        return new StartNodeDataDO.Event();
    }

    /**
     * Create an instance of {@link StartNodeDataDO.Event.RequestVars }
     */
    public StartNodeDataDO.Event.RequestVars createBatchLogicalUnitStartNodeDataDOEventRequestVars() {
        return new StartNodeDataDO.Event.RequestVars();
    }

    /**
     * Create an instance of {@link StartNodeDataDO.Event.RequestVars.IBVariableDO }
     */
    public StartNodeDataDO.Event.RequestVars.IBVariableDO createBatchLogicalUnitStartNodeDataDOEventRequestVarsIBVariableDO() {
        return new StartNodeDataDO.Event.RequestVars.IBVariableDO();
    }

    /**
     * Create an instance of {@link StartNodeDataDO.Event.ReplyVars }
     */
    public StartNodeDataDO.Event.ReplyVars createBatchLogicalUnitStartNodeDataDOEventReplyVars() {
        return new StartNodeDataDO.Event.ReplyVars();
    }

    /**
     * Create an instance of {@link StartNodeDataDO.Event.ReplyVars.IBVariableDO }
     */
    public StartNodeDataDO.Event.ReplyVars.IBVariableDO createBatchLogicalUnitStartNodeDataDOEventReplyVarsIBVariableDO() {
        return new StartNodeDataDO.Event.ReplyVars.IBVariableDO();
    }

    /**
     * Create an instance of {@link StartNodeDataDO.Event.ReplyVars.IBVariableDO.ErrorValue }
     */
    public StartNodeDataDO.Event.ReplyVars.IBVariableDO.ErrorValue createBatchLogicalUnitStartNodeDataDOEventReplyVarsIBVariableDOErrorValue() {
        return new StartNodeDataDO.Event.ReplyVars.IBVariableDO.ErrorValue();
    }

    /**
     * Create an instance of {@link FlowDO }
     */
    public FlowDO createBatchLogicalUnitFlowDO() {
        return new FlowDO();
    }

    /**
     * Create an instance of {@link FlowDO.UserRoles }
     */
    public FlowDO.UserRoles createBatchLogicalUnitFlowDOUserRoles() {
        return new FlowDO.UserRoles();
    }

    /**
     * Create an instance of {@link FlowDO.UserRoles.UserAndGroupDO }
     */
    public FlowDO.UserRoles.UserAndGroupDO createBatchLogicalUnitFlowDOUserRolesUserAndGroupDO() {
        return new FlowDO.UserRoles.UserAndGroupDO();
    }

    /**
     * Create an instance of {@link FlowDO.TestCases }
     */
    public FlowDO.TestCases createBatchLogicalUnitFlowDOTestCases() {
        return new FlowDO.TestCases();
    }

    /**
     * Create an instance of {@link FlowDO.TestCases.TestCaseDO }
     */
    public FlowDO.TestCases.TestCaseDO createBatchLogicalUnitFlowDOTestCasesTestCaseDO() {
        return new FlowDO.TestCases.TestCaseDO();
    }

    /**
     * Create an instance of {@link FlowDO.TestCases.TestCaseDO.Results }
     */
    public FlowDO.TestCases.TestCaseDO.Results createBatchLogicalUnitFlowDOTestCasesTestCaseDOResults() {
        return new FlowDO.TestCases.TestCaseDO.Results();
    }

    /**
     * Create an instance of {@link FlowDO.TestCases.TestCaseDO.RequestVars }
     */
    public FlowDO.TestCases.TestCaseDO.RequestVars createBatchLogicalUnitFlowDOTestCasesTestCaseDORequestVars() {
        return new FlowDO.TestCases.TestCaseDO.RequestVars();
    }

    /**
     * Create an instance of {@link FlowDO.TestCases.TestCaseDO.RequestVars.IBVariableDO }
     */
    public FlowDO.TestCases.TestCaseDO.RequestVars.IBVariableDO createBatchLogicalUnitFlowDOTestCasesTestCaseDORequestVarsIBVariableDO() {
        return new FlowDO.TestCases.TestCaseDO.RequestVars.IBVariableDO();
    }

    /**
     * Create an instance of {@link FlowDO.StandardReply }
     */
    public FlowDO.StandardReply createBatchLogicalUnitFlowDOStandardReply() {
        return new FlowDO.StandardReply();
    }

    /**
     * Create an instance of {@link FlowDO.StandardReply.EventReply }
     */
    public FlowDO.StandardReply.EventReply createBatchLogicalUnitFlowDOStandardReplyEventReply() {
        return new FlowDO.StandardReply.EventReply();
    }

    /**
     * Create an instance of {@link FlowDO.StandardReply.EventReply.ReplyVars }
     */
    public FlowDO.StandardReply.EventReply.ReplyVars createBatchLogicalUnitFlowDOStandardReplyEventReplyReplyVars() {
        return new FlowDO.StandardReply.EventReply.ReplyVars();
    }

    /**
     * Create an instance of {@link FlowDO.StandardReply.EventReply.ReplyVars.IBVariableDO }
     */
    public FlowDO.StandardReply.EventReply.ReplyVars.IBVariableDO createBatchLogicalUnitFlowDOStandardReplyEventReplyReplyVarsIBVariableDO() {
        return new FlowDO.StandardReply.EventReply.ReplyVars.IBVariableDO();
    }

    /**
     * Create an instance of {@link FlowDO.StandardReply.EventReply.ReplyVars.IBVariableDO.ErrorValue }
     */
    public FlowDO.StandardReply.EventReply.ReplyVars.IBVariableDO.ErrorValue createBatchLogicalUnitFlowDOStandardReplyEventReplyReplyVarsIBVariableDOErrorValue() {
        return new FlowDO.StandardReply.EventReply.ReplyVars.IBVariableDO.ErrorValue();
    }

    /**
     * Create an instance of {@link FlowDO.StandardReply.CellNodeData }
     */
    public FlowDO.StandardReply.CellNodeData createBatchLogicalUnitFlowDOStandardReplyCellNodeData() {
        return new FlowDO.StandardReply.CellNodeData();
    }

    /**
     * Create an instance of {@link FlowDO.Schedule }
     */
    public FlowDO.Schedule createBatchLogicalUnitFlowDOSchedule() {
        return new FlowDO.Schedule();
    }

    /**
     * Create an instance of {@link FlowDO.ConfiguredNotifications }
     */
    public FlowDO.ConfiguredNotifications createBatchLogicalUnitFlowDOConfiguredNotifications() {
        return new FlowDO.ConfiguredNotifications();
    }

    /**
     * Create an instance of {@link FlowDO.ConfiguredNotifications.NotificationDO }
     */
    public FlowDO.ConfiguredNotifications.NotificationDO createBatchLogicalUnitFlowDOConfiguredNotificationsNotificationDO() {
        return new FlowDO.ConfiguredNotifications.NotificationDO();
    }

    /**
     * Create an instance of {@link FlowDO.ConfiguredNotifications.NotificationDO.Events }
     */
    public FlowDO.ConfiguredNotifications.NotificationDO.Events createBatchLogicalUnitFlowDOConfiguredNotificationsNotificationDOEvents() {
        return new FlowDO.ConfiguredNotifications.NotificationDO.Events();
    }

    /**
     * Create an instance of {@link FlowDO.ConfiguredNotifications.NotificationDO.Events.NotificationEventDO }
     */
    public FlowDO.ConfiguredNotifications.NotificationDO.Events.NotificationEventDO createBatchLogicalUnitFlowDOConfiguredNotificationsNotificationDOEventsNotificationEventDO() {
        return new FlowDO.ConfiguredNotifications.NotificationDO.Events.NotificationEventDO();
    }

    /**
     * Create an instance of {@link CampaignDO }
     */
    public CampaignDO createBatchLogicalUnitCampaignDO() {
        return new CampaignDO();
    }

    /**
     * Create an instance of {@link CampaignDO.VersionHistory }
     */
    public CampaignDO.VersionHistory createBatchLogicalUnitCampaignDOVersionHistory() {
        return new CampaignDO.VersionHistory();
    }

    /**
     * Create an instance of {@link CampaignDO.VersionHistory.VersionEntries }
     */
    public CampaignDO.VersionHistory.VersionEntries createBatchLogicalUnitCampaignDOVersionHistoryVersionEntries() {
        return new CampaignDO.VersionHistory.VersionEntries();
    }

    /**
     * Create an instance of {@link CampaignDO.Definition }
     */
    public CampaignDO.Definition createBatchLogicalUnitCampaignDODefinition() {
        return new CampaignDO.Definition();
    }

    /**
     * Create an instance of {@link CampaignDO.Definition.StatusList }
     */
    public CampaignDO.Definition.StatusList createBatchLogicalUnitCampaignDODefinitionStatusList() {
        return new CampaignDO.Definition.StatusList();
    }

    /**
     * Create an instance of {@link CampaignDO.Definition.SharedIn }
     */
    public CampaignDO.Definition.SharedIn createBatchLogicalUnitCampaignDODefinitionSharedIn() {
        return new CampaignDO.Definition.SharedIn();
    }

    /**
     * Create an instance of {@link CampaignDO.Definition.Schedule }
     */
    public CampaignDO.Definition.Schedule createBatchLogicalUnitCampaignDODefinitionSchedule() {
        return new CampaignDO.Definition.Schedule();
    }

    /**
     * Create an instance of {@link CampaignDO.Definition.PageConfigurations }
     */
    public CampaignDO.Definition.PageConfigurations createBatchLogicalUnitCampaignDODefinitionPageConfigurations() {
        return new CampaignDO.Definition.PageConfigurations();
    }

    /**
     * Create an instance of {@link CampaignDO.Definition.PageConfigurations.PageConfigDO }
     */
    public CampaignDO.Definition.PageConfigurations.PageConfigDO createBatchLogicalUnitCampaignDODefinitionPageConfigurationsPageConfigDO() {
        return new CampaignDO.Definition.PageConfigurations.PageConfigDO();
    }

    /**
     * Create an instance of {@link CampaignDO.Definition.PageConfigurations.PageConfigDO.ProcessPages }
     */
    public CampaignDO.Definition.PageConfigurations.PageConfigDO.ProcessPages createBatchLogicalUnitCampaignDODefinitionPageConfigurationsPageConfigDOProcessPages() {
        return new CampaignDO.Definition.PageConfigurations.PageConfigDO.ProcessPages();
    }

    /**
     * Create an instance of {@link CampaignDO.Definition.PageConfigurations.PageConfigDO.DesignPages }
     */
    public CampaignDO.Definition.PageConfigurations.PageConfigDO.DesignPages createBatchLogicalUnitCampaignDODefinitionPageConfigurationsPageConfigDODesignPages() {
        return new CampaignDO.Definition.PageConfigurations.PageConfigDO.DesignPages();
    }

    /**
     * Create an instance of {@link CampaignDO.Definition.CheckListItems }
     */
    public CampaignDO.Definition.CheckListItems createBatchLogicalUnitCampaignDODefinitionCheckListItems() {
        return new CampaignDO.Definition.CheckListItems();
    }

    /**
     * Create an instance of {@link CampaignDO.Definition.CheckList }
     */
    public CampaignDO.Definition.CheckList createBatchLogicalUnitCampaignDODefinitionCheckList() {
        return new CampaignDO.Definition.CheckList();
    }

    /**
     * Create an instance of {@link CampaignDO.Definition.CheckList.Steps }
     */
    public CampaignDO.Definition.CheckList.Steps createBatchLogicalUnitCampaignDODefinitionCheckListSteps() {
        return new CampaignDO.Definition.CheckList.Steps();
    }

    /**
     * Create an instance of {@link CampaignDO.Definition.BriefData }
     */
    public CampaignDO.Definition.BriefData createBatchLogicalUnitCampaignDODefinitionBriefData() {
        return new CampaignDO.Definition.BriefData();
    }

    /**
     * Create an instance of {@link CampaignDO.Definition.Approvers }
     */
    public CampaignDO.Definition.Approvers createBatchLogicalUnitCampaignDODefinitionApprovers() {
        return new CampaignDO.Definition.Approvers();
    }

    /**
     * Create an instance of {@link CampaignDO.Definition.Approvers.UserAndGroupDO }
     */
    public CampaignDO.Definition.Approvers.UserAndGroupDO createBatchLogicalUnitCampaignDODefinitionApproversUserAndGroupDO() {
        return new CampaignDO.Definition.Approvers.UserAndGroupDO();
    }

    /**
     * Create an instance of {@link CampaignDO.Definition.AccessControls }
     */
    public CampaignDO.Definition.AccessControls createBatchLogicalUnitCampaignDODefinitionAccessControls() {
        return new CampaignDO.Definition.AccessControls();
    }

    /**
     * Create an instance of {@link CampaignDO.Definition.AccessControls.UserAndGroupDO }
     */
    public CampaignDO.Definition.AccessControls.UserAndGroupDO createBatchLogicalUnitCampaignDODefinitionAccessControlsUserAndGroupDO() {
        return new CampaignDO.Definition.AccessControls.UserAndGroupDO();
    }

    /**
     * Create an instance of {@link CampaignDO.CheckListItems }
     */
    public CampaignDO.CheckListItems createBatchLogicalUnitCampaignDOCheckListItems() {
        return new CampaignDO.CheckListItems();
    }

    /**
     * Create an instance of {@link Batch.ResultsSummary }
     */
    public Batch.ResultsSummary createBatchResultsSummary() {
        return new Batch.ResultsSummary();
    }

    /**
     * Create an instance of {@link Batch.ExtractedFrom }
     */
    public Batch.ExtractedFrom createBatchExtractedFrom() {
        return new Batch.ExtractedFrom();
    }

    /**
     * Create an instance of {@link ProcessNodeDataDO.InputNodes }
     */
    public ProcessNodeDataDO.InputNodes createBatchLogicalUnitProcessNodeDataDOInputNodes() {
        return new ProcessNodeDataDO.InputNodes();
    }

    /**
     * Create an instance of {@link ProcessNodeDataDO.NodeTags }
     */
    public ProcessNodeDataDO.NodeTags createBatchLogicalUnitProcessNodeDataDONodeTags() {
        return new ProcessNodeDataDO.NodeTags();
    }

    /**
     * Create an instance of {@link ProcessNodeDataDO.OutputNodes }
     */
    public ProcessNodeDataDO.OutputNodes createBatchLogicalUnitProcessNodeDataDOOutputNodes() {
        return new ProcessNodeDataDO.OutputNodes();
    }

    /**
     * Create an instance of {@link ProcessNodeDataDO.SortByList }
     */
    public ProcessNodeDataDO.SortByList createBatchLogicalUnitProcessNodeDataDOSortByList() {
        return new ProcessNodeDataDO.SortByList();
    }

    /**
     * Create an instance of {@link ProcessNodeDataDO.Splitters }
     */
    public ProcessNodeDataDO.Splitters createBatchLogicalUnitProcessNodeDataDOSplitters() {
        return new ProcessNodeDataDO.Splitters();
    }

    /**
     * Create an instance of {@link ProcessNodeDataDO.SystemExtraValues }
     */
    public ProcessNodeDataDO.SystemExtraValues createBatchLogicalUnitProcessNodeDataDOSystemExtraValues() {
        return new ProcessNodeDataDO.SystemExtraValues();
    }

    /**
     * Create an instance of {@link ProcessNodeDataDO.Process.ArbitrationUDFSelectionTags }
     */
    public ProcessNodeDataDO.Process.ArbitrationUDFSelectionTags createBatchLogicalUnitProcessNodeDataDOProcessArbitrationUDFSelectionTags() {
        return new ProcessNodeDataDO.Process.ArbitrationUDFSelectionTags();
    }

    /**
     * Create an instance of {@link ProcessNodeDataDO.Process.BrmInfo }
     */
    public ProcessNodeDataDO.Process.BrmInfo createBatchLogicalUnitProcessNodeDataDOProcessBrmInfo() {
        return new ProcessNodeDataDO.Process.BrmInfo();
    }

    /**
     * Create an instance of {@link ProcessNodeDataDO.Process.Folder }
     */
    public ProcessNodeDataDO.Process.Folder createBatchLogicalUnitProcessNodeDataDOProcessFolder() {
        return new ProcessNodeDataDO.Process.Folder();
    }

    /**
     * Create an instance of {@link ProcessNodeDataDO.Process.MethodInfo }
     */
    public ProcessNodeDataDO.Process.MethodInfo createBatchLogicalUnitProcessNodeDataDOProcessMethodInfo() {
        return new ProcessNodeDataDO.Process.MethodInfo();
    }

    /**
     * Create an instance of {@link ProcessNodeDataDO.Process.SharedIn }
     */
    public ProcessNodeDataDO.Process.SharedIn createBatchLogicalUnitProcessNodeDataDOProcessSharedIn() {
        return new ProcessNodeDataDO.Process.SharedIn();
    }

    /**
     * Create an instance of {@link ProcessNodeDataDO.Process.OutputVariableList.IBVariableDO.SharedIn }
     */
    public ProcessNodeDataDO.Process.OutputVariableList.IBVariableDO.SharedIn createBatchLogicalUnitProcessNodeDataDOProcessOutputVariableListIBVariableDOSharedIn() {
        return new ProcessNodeDataDO.Process.OutputVariableList.IBVariableDO.SharedIn();
    }

    /**
     * Create an instance of {@link ProcessNodeDataDO.Process.InputVariableList.IBVariableDO.SharedIn }
     */
    public ProcessNodeDataDO.Process.InputVariableList.IBVariableDO.SharedIn createBatchLogicalUnitProcessNodeDataDOProcessInputVariableListIBVariableDOSharedIn() {
        return new ProcessNodeDataDO.Process.InputVariableList.IBVariableDO.SharedIn();
    }

    /**
     * Create an instance of {@link ValueTypeVarInfoDO }
     */
    public ValueTypeVarInfoDO createBatchLogicalUnitProcessNodeDataDOProcessInputVariableListIBVariableDOValueValueTypeVarInfoDO() {
        return new ValueTypeVarInfoDO();
    }

    /**
     * Create an instance of {@link ProcessNodeDataDO.Process.InputVariableList.IBVariableDO.Identifier.SharedIn }
     */
    public ProcessNodeDataDO.Process.InputVariableList.IBVariableDO.Identifier.SharedIn createBatchLogicalUnitProcessNodeDataDOProcessInputVariableListIBVariableDOIdentifierSharedIn() {
        return new ProcessNodeDataDO.Process.InputVariableList.IBVariableDO.Identifier.SharedIn();
    }

    /**
     * Create an instance of {@link ProcessNodeDataDO.Process.DatagridIdentifier.SharedIn }
     */
    public ProcessNodeDataDO.Process.DatagridIdentifier.SharedIn createBatchLogicalUnitProcessNodeDataDOProcessDatagridIdentifierSharedIn() {
        return new ProcessNodeDataDO.Process.DatagridIdentifier.SharedIn();
    }

    /**
     * Create an instance of {@link CellNodeDataDO.AncestorLinkNodes }
     */
    public CellNodeDataDO.AncestorLinkNodes createBatchLogicalUnitCellNodeDataDOAncestorLinkNodes() {
        return new CellNodeDataDO.AncestorLinkNodes();
    }

    /**
     * Create an instance of {@link CellNodeDataDO.InputNodes }
     */
    public CellNodeDataDO.InputNodes createBatchLogicalUnitCellNodeDataDOInputNodes() {
        return new CellNodeDataDO.InputNodes();
    }

    /**
     * Create an instance of {@link CellNodeDataDO.NodeTags }
     */
    public CellNodeDataDO.NodeTags createBatchLogicalUnitCellNodeDataDONodeTags() {
        return new CellNodeDataDO.NodeTags();
    }

    /**
     * Create an instance of {@link CellNodeDataDO.OutputNodes }
     */
    public CellNodeDataDO.OutputNodes createBatchLogicalUnitCellNodeDataDOOutputNodes() {
        return new CellNodeDataDO.OutputNodes();
    }

    /**
     * Create an instance of {@link CellNodeDataDO.SortByList }
     */
    public CellNodeDataDO.SortByList createBatchLogicalUnitCellNodeDataDOSortByList() {
        return new CellNodeDataDO.SortByList();
    }

    /**
     * Create an instance of {@link CellNodeDataDO.Splitters }
     */
    public CellNodeDataDO.Splitters createBatchLogicalUnitCellNodeDataDOSplitters() {
        return new CellNodeDataDO.Splitters();
    }

    /**
     * Create an instance of {@link CellNodeDataDO.SystemExtraValues }
     */
    public CellNodeDataDO.SystemExtraValues createBatchLogicalUnitCellNodeDataDOSystemExtraValues() {
        return new CellNodeDataDO.SystemExtraValues();
    }

    /**
     * Create an instance of {@link SplitNodeDataDO.InputNodes }
     */
    public SplitNodeDataDO.InputNodes createBatchLogicalUnitSplitNodeDataDOInputNodes() {
        return new SplitNodeDataDO.InputNodes();
    }

    /**
     * Create an instance of {@link SplitNodeDataDO.NodeTags }
     */
    public SplitNodeDataDO.NodeTags createBatchLogicalUnitSplitNodeDataDONodeTags() {
        return new SplitNodeDataDO.NodeTags();
    }

    /**
     * Create an instance of {@link SplitNodeDataDO.OutputNodes }
     */
    public SplitNodeDataDO.OutputNodes createBatchLogicalUnitSplitNodeDataDOOutputNodes() {
        return new SplitNodeDataDO.OutputNodes();
    }

    /**
     * Create an instance of {@link SplitNodeDataDO.SortByList }
     */
    public SplitNodeDataDO.SortByList createBatchLogicalUnitSplitNodeDataDOSortByList() {
        return new SplitNodeDataDO.SortByList();
    }

    /**
     * Create an instance of {@link SplitNodeDataDO.SplitCriteriaList }
     */
    public SplitNodeDataDO.SplitCriteriaList createBatchLogicalUnitSplitNodeDataDOSplitCriteriaList() {
        return new SplitNodeDataDO.SplitCriteriaList();
    }

    /**
     * Create an instance of {@link SplitNodeDataDO.Splitters }
     */
    public SplitNodeDataDO.Splitters createBatchLogicalUnitSplitNodeDataDOSplitters() {
        return new SplitNodeDataDO.Splitters();
    }

    /**
     * Create an instance of {@link SplitNodeDataDO.SystemExtraValues }
     */
    public SplitNodeDataDO.SystemExtraValues createBatchLogicalUnitSplitNodeDataDOSystemExtraValues() {
        return new SplitNodeDataDO.SystemExtraValues();
    }

    /**
     * Create an instance of {@link SplitNodeDataDO.SplitOnNodeDataDO.NodeTags }
     */
    public SplitNodeDataDO.SplitOnNodeDataDO.NodeTags createBatchLogicalUnitSplitNodeDataDOSplitOnNodeDataDONodeTags() {
        return new SplitNodeDataDO.SplitOnNodeDataDO.NodeTags();
    }

    /**
     * Create an instance of {@link SplitNodeDataDO.SplitOnNodeDataDO.SelectedItemsCache }
     */
    public SplitNodeDataDO.SplitOnNodeDataDO.SelectedItemsCache createBatchLogicalUnitSplitNodeDataDOSplitOnNodeDataDOSelectedItemsCache() {
        return new SplitNodeDataDO.SplitOnNodeDataDO.SelectedItemsCache();
    }

    /**
     * Create an instance of {@link SplitNodeDataDO.SplitOnNodeDataDO.SortByList }
     */
    public SplitNodeDataDO.SplitOnNodeDataDO.SortByList createBatchLogicalUnitSplitNodeDataDOSplitOnNodeDataDOSortByList() {
        return new SplitNodeDataDO.SplitOnNodeDataDO.SortByList();
    }

    /**
     * Create an instance of {@link SplitNodeDataDO.SplitOnNodeDataDO.Splitters }
     */
    public SplitNodeDataDO.SplitOnNodeDataDO.Splitters createBatchLogicalUnitSplitNodeDataDOSplitOnNodeDataDOSplitters() {
        return new SplitNodeDataDO.SplitOnNodeDataDO.Splitters();
    }

    /**
     * Create an instance of {@link SplitNodeDataDO.SplitOnNodeDataDO.VarRefDO }
     */
    public SplitNodeDataDO.SplitOnNodeDataDO.VarRefDO createBatchLogicalUnitSplitNodeDataDOSplitOnNodeDataDOVarRefDO() {
        return new SplitNodeDataDO.SplitOnNodeDataDO.VarRefDO();
    }

    /**
     * Create an instance of {@link SplitNodeDataDO.LineItems.SplitNodeLineItemDO.RequiredCount }
     */
    public SplitNodeDataDO.LineItems.SplitNodeLineItemDO.RequiredCount createBatchLogicalUnitSplitNodeDataDOLineItemsSplitNodeLineItemDORequiredCount() {
        return new SplitNodeDataDO.LineItems.SplitNodeLineItemDO.RequiredCount();
    }

    /**
     * Create an instance of {@link SplitNodeDataDO.LineItems.SplitNodeLineItemDO.RequiredPercent }
     */
    public SplitNodeDataDO.LineItems.SplitNodeLineItemDO.RequiredPercent createBatchLogicalUnitSplitNodeDataDOLineItemsSplitNodeLineItemDORequiredPercent() {
        return new SplitNodeDataDO.LineItems.SplitNodeLineItemDO.RequiredPercent();
    }

    /**
     * Create an instance of {@link ReplyNodeDataDO.InputNodes }
     */
    public ReplyNodeDataDO.InputNodes createBatchLogicalUnitReplyNodeDataDOInputNodes() {
        return new ReplyNodeDataDO.InputNodes();
    }

    /**
     * Create an instance of {@link ReplyNodeDataDO.NodeTags }
     */
    public ReplyNodeDataDO.NodeTags createBatchLogicalUnitReplyNodeDataDONodeTags() {
        return new ReplyNodeDataDO.NodeTags();
    }

    /**
     * Create an instance of {@link ReplyNodeDataDO.OutputNodes }
     */
    public ReplyNodeDataDO.OutputNodes createBatchLogicalUnitReplyNodeDataDOOutputNodes() {
        return new ReplyNodeDataDO.OutputNodes();
    }

    /**
     * Create an instance of {@link ReplyNodeDataDO.SortByList }
     */
    public ReplyNodeDataDO.SortByList createBatchLogicalUnitReplyNodeDataDOSortByList() {
        return new ReplyNodeDataDO.SortByList();
    }

    /**
     * Create an instance of {@link ReplyNodeDataDO.Splitters }
     */
    public ReplyNodeDataDO.Splitters createBatchLogicalUnitReplyNodeDataDOSplitters() {
        return new ReplyNodeDataDO.Splitters();
    }

    /**
     * Create an instance of {@link ReplyNodeDataDO.SubjectVariables }
     */
    public ReplyNodeDataDO.SubjectVariables createBatchLogicalUnitReplyNodeDataDOSubjectVariables() {
        return new ReplyNodeDataDO.SubjectVariables();
    }

    /**
     * Create an instance of {@link ReplyNodeDataDO.EventReply.ReplyVars.IBVariableDO.SharedIn }
     */
    public ReplyNodeDataDO.EventReply.ReplyVars.IBVariableDO.SharedIn createBatchLogicalUnitReplyNodeDataDOEventReplyReplyVarsIBVariableDOSharedIn() {
        return new ReplyNodeDataDO.EventReply.ReplyVars.IBVariableDO.SharedIn();
    }

    /**
     * Create an instance of {@link ReplyNodeDataDO.EventReply.ReplyVars.IBVariableDO.Value.ValueTypeVarInfoDO }
     */
    public ReplyNodeDataDO.EventReply.ReplyVars.IBVariableDO.Value.ValueTypeVarInfoDO createBatchLogicalUnitReplyNodeDataDOEventReplyReplyVarsIBVariableDOValueValueTypeVarInfoDO() {
        return new ReplyNodeDataDO.EventReply.ReplyVars.IBVariableDO.Value.ValueTypeVarInfoDO();
    }

    /**
     * Create an instance of {@link ReplyNodeDataDO.EventReply.ReplyVars.IBVariableDO.ErrorValue.ValueTypeVarInfoDO }
     */
    public ReplyNodeDataDO.EventReply.ReplyVars.IBVariableDO.ErrorValue.ValueTypeVarInfoDO createBatchLogicalUnitReplyNodeDataDOEventReplyReplyVarsIBVariableDOErrorValueValueTypeVarInfoDO() {
        return new ReplyNodeDataDO.EventReply.ReplyVars.IBVariableDO.ErrorValue.ValueTypeVarInfoDO();
    }

    /**
     * Create an instance of {@link ReplyNodeDataDO.Definition.Folder }
     */
    public ReplyNodeDataDO.Definition.Folder createBatchLogicalUnitReplyNodeDataDODefinitionFolder() {
        return new ReplyNodeDataDO.Definition.Folder();
    }

    /**
     * Create an instance of {@link ReplyNodeDataDO.Definition.ImportDetails }
     */
    public ReplyNodeDataDO.Definition.ImportDetails createBatchLogicalUnitReplyNodeDataDODefinitionImportDetails() {
        return new ReplyNodeDataDO.Definition.ImportDetails();
    }

    /**
     * Create an instance of {@link ReplyNodeDataDO.Definition.ResponseList }
     */
    public ReplyNodeDataDO.Definition.ResponseList createBatchLogicalUnitReplyNodeDataDODefinitionResponseList() {
        return new ReplyNodeDataDO.Definition.ResponseList();
    }

    /**
     * Create an instance of {@link ReplyNodeDataDO.Definition.SharedIn }
     */
    public ReplyNodeDataDO.Definition.SharedIn createBatchLogicalUnitReplyNodeDataDODefinitionSharedIn() {
        return new ReplyNodeDataDO.Definition.SharedIn();
    }

    /**
     * Create an instance of {@link ReplyNodeDataDO.ContactHistoryVariables.IBVariableDO.SharedIn }
     */
    public ReplyNodeDataDO.ContactHistoryVariables.IBVariableDO.SharedIn createBatchLogicalUnitReplyNodeDataDOContactHistoryVariablesIBVariableDOSharedIn() {
        return new ReplyNodeDataDO.ContactHistoryVariables.IBVariableDO.SharedIn();
    }

    /**
     * Create an instance of {@link ReplyNodeDataDO.AudienceList.AudienceDO.PackageDO }
     */
    public ReplyNodeDataDO.AudienceList.AudienceDO.PackageDO createBatchLogicalUnitReplyNodeDataDOAudienceListAudienceDOPackageDO() {
        return new ReplyNodeDataDO.AudienceList.AudienceDO.PackageDO();
    }

    /**
     * Create an instance of {@link ReplyNodeDataDO.AudienceList.AudienceDO.RemoveStagedTreatmentsChannels }
     */
    public ReplyNodeDataDO.AudienceList.AudienceDO.RemoveStagedTreatmentsChannels createBatchLogicalUnitReplyNodeDataDOAudienceListAudienceDORemoveStagedTreatmentsChannels() {
        return new ReplyNodeDataDO.AudienceList.AudienceDO.RemoveStagedTreatmentsChannels();
    }

    /**
     * Create an instance of {@link StartNodeDataDO.InputNodes }
     */
    public StartNodeDataDO.InputNodes createBatchLogicalUnitStartNodeDataDOInputNodes() {
        return new StartNodeDataDO.InputNodes();
    }

    /**
     * Create an instance of {@link StartNodeDataDO.NodeTags }
     */
    public StartNodeDataDO.NodeTags createBatchLogicalUnitStartNodeDataDONodeTags() {
        return new StartNodeDataDO.NodeTags();
    }

    /**
     * Create an instance of {@link StartNodeDataDO.OutputNodes }
     */
    public StartNodeDataDO.OutputNodes createBatchLogicalUnitStartNodeDataDOOutputNodes() {
        return new StartNodeDataDO.OutputNodes();
    }

    /**
     * Create an instance of {@link StartNodeDataDO.SortByList }
     */
    public StartNodeDataDO.SortByList createBatchLogicalUnitStartNodeDataDOSortByList() {
        return new StartNodeDataDO.SortByList();
    }

    /**
     * Create an instance of {@link StartNodeDataDO.Splitters }
     */
    public StartNodeDataDO.Splitters createBatchLogicalUnitStartNodeDataDOSplitters() {
        return new StartNodeDataDO.Splitters();
    }

    /**
     * Create an instance of {@link StartNodeDataDO.SystemExtraValues }
     */
    public StartNodeDataDO.SystemExtraValues createBatchLogicalUnitStartNodeDataDOSystemExtraValues() {
        return new StartNodeDataDO.SystemExtraValues();
    }

    /**
     * Create an instance of {@link StartNodeDataDO.Event.SharedIn }
     */
    public StartNodeDataDO.Event.SharedIn createBatchLogicalUnitStartNodeDataDOEventSharedIn() {
        return new StartNodeDataDO.Event.SharedIn();
    }

    /**
     * Create an instance of {@link StartNodeDataDO.Event.RequestVars.IBVariableDO.SharedIn }
     */
    public StartNodeDataDO.Event.RequestVars.IBVariableDO.SharedIn createBatchLogicalUnitStartNodeDataDOEventRequestVarsIBVariableDOSharedIn() {
        return new StartNodeDataDO.Event.RequestVars.IBVariableDO.SharedIn();
    }

    /**
     * Create an instance of {@link StartNodeDataDO.Event.ReplyVars.IBVariableDO.SharedIn }
     */
    public StartNodeDataDO.Event.ReplyVars.IBVariableDO.SharedIn createBatchLogicalUnitStartNodeDataDOEventReplyVarsIBVariableDOSharedIn() {
        return new StartNodeDataDO.Event.ReplyVars.IBVariableDO.SharedIn();
    }

    /**
     * Create an instance of {@link StartNodeDataDO.Event.ReplyVars.IBVariableDO.ErrorValue.ValueTypeVarInfoDO }
     */
    public ValueTypeVarInfoDO createBatchLogicalUnitStartNodeDataDOEventReplyVarsIBVariableDOErrorValueValueTypeVarInfoDO() {
        return new ValueTypeVarInfoDO();
    }

    /**
     * Create an instance of {@link FlowDO.CalculatedDataItemList }
     */
    public FlowDO.CalculatedDataItemList createBatchLogicalUnitFlowDOCalculatedDataItemList() {
        return new FlowDO.CalculatedDataItemList();
    }

    /**
     * Create an instance of {@link FlowDO.CampaignTreatmentSetsReferenced }
     */
    public FlowDO.CampaignTreatmentSetsReferenced createBatchLogicalUnitFlowDOCampaignTreatmentSetsReferenced() {
        return new FlowDO.CampaignTreatmentSetsReferenced();
    }

    /**
     * Create an instance of {@link FlowDO.EditorList }
     */
    public FlowDO.EditorList createBatchLogicalUnitFlowDOEditorList() {
        return new FlowDO.EditorList();
    }

    /**
     * Create an instance of {@link FlowDO.FixupStatus }
     */
    public FlowDO.FixupStatus createBatchLogicalUnitFlowDOFixupStatus() {
        return new FlowDO.FixupStatus();
    }

    /**
     * Create an instance of {@link FlowDO.FolderDO }
     */
    public FlowDO.FolderDO createBatchLogicalUnitFlowDOFolderDO() {
        return new FlowDO.FolderDO();
    }

    /**
     * Create an instance of {@link FlowDO.GlobalVariableReferences }
     */
    public FlowDO.GlobalVariableReferences createBatchLogicalUnitFlowDOGlobalVariableReferences() {
        return new FlowDO.GlobalVariableReferences();
    }

    /**
     * Create an instance of {@link FlowDO.IdentifierReferences }
     */
    public FlowDO.IdentifierReferences createBatchLogicalUnitFlowDOIdentifierReferences() {
        return new FlowDO.IdentifierReferences();
    }

    /**
     * Create an instance of {@link FlowDO.ImplicitProcessReferences }
     */
    public FlowDO.ImplicitProcessReferences createBatchLogicalUnitFlowDOImplicitProcessReferences() {
        return new FlowDO.ImplicitProcessReferences();
    }

    /**
     * Create an instance of {@link FlowDO.NodeGroupList }
     */
    public FlowDO.NodeGroupList createBatchLogicalUnitFlowDONodeGroupList() {
        return new FlowDO.NodeGroupList();
    }

    /**
     * Create an instance of {@link FlowDO.NoteList }
     */
    public FlowDO.NoteList createBatchLogicalUnitFlowDONoteList() {
        return new FlowDO.NoteList();
    }

    /**
     * Create an instance of {@link FlowDO.ViewerList }
     */
    public FlowDO.ViewerList createBatchLogicalUnitFlowDOViewerList() {
        return new FlowDO.ViewerList();
    }

    /**
     * Create an instance of {@link FlowDO.ZOrderIdList }
     */
    public FlowDO.ZOrderIdList createBatchLogicalUnitFlowDOZOrderIdList() {
        return new FlowDO.ZOrderIdList();
    }

    /**
     * Create an instance of {@link FlowDO.UserRoles.UserAndGroupDO.Members }
     */
    public FlowDO.UserRoles.UserAndGroupDO.Members createBatchLogicalUnitFlowDOUserRolesUserAndGroupDOMembers() {
        return new FlowDO.UserRoles.UserAndGroupDO.Members();
    }

    /**
     * Create an instance of {@link FlowDO.TestCases.TestCaseDO.GlobalVars }
     */
    public FlowDO.TestCases.TestCaseDO.GlobalVars createBatchLogicalUnitFlowDOTestCasesTestCaseDOGlobalVars() {
        return new FlowDO.TestCases.TestCaseDO.GlobalVars();
    }

    /**
     * Create an instance of {@link FlowDO.TestCases.TestCaseDO.ReplyVars }
     */
    public FlowDO.TestCases.TestCaseDO.ReplyVars createBatchLogicalUnitFlowDOTestCasesTestCaseDOReplyVars() {
        return new FlowDO.TestCases.TestCaseDO.ReplyVars();
    }

    /**
     * Create an instance of {@link FlowDO.TestCases.TestCaseDO.Results.ExecutedNodePath }
     */
    public FlowDO.TestCases.TestCaseDO.Results.ExecutedNodePath createBatchLogicalUnitFlowDOTestCasesTestCaseDOResultsExecutedNodePath() {
        return new FlowDO.TestCases.TestCaseDO.Results.ExecutedNodePath();
    }

    /**
     * Create an instance of {@link FlowDO.TestCases.TestCaseDO.RequestVars.IBVariableDO.SharedIn }
     */
    public FlowDO.TestCases.TestCaseDO.RequestVars.IBVariableDO.SharedIn createBatchLogicalUnitFlowDOTestCasesTestCaseDORequestVarsIBVariableDOSharedIn() {
        return new FlowDO.TestCases.TestCaseDO.RequestVars.IBVariableDO.SharedIn();
    }

    /**
     * Create an instance of {@link FlowDO.TestCases.TestCaseDO.RequestVars.IBVariableDO.Value }
     */
    public FlowDO.TestCases.TestCaseDO.RequestVars.IBVariableDO.Value createBatchLogicalUnitFlowDOTestCasesTestCaseDORequestVarsIBVariableDOValue() {
        return new FlowDO.TestCases.TestCaseDO.RequestVars.IBVariableDO.Value();
    }

    /**
     * Create an instance of {@link FlowDO.StandardReply.ContactHistoryVariables }
     */
    public FlowDO.StandardReply.ContactHistoryVariables createBatchLogicalUnitFlowDOStandardReplyContactHistoryVariables() {
        return new FlowDO.StandardReply.ContactHistoryVariables();
    }

    /**
     * Create an instance of {@link FlowDO.StandardReply.PackageDO }
     */
    public FlowDO.StandardReply.PackageDO createBatchLogicalUnitFlowDOStandardReplyPackageDO() {
        return new FlowDO.StandardReply.PackageDO();
    }

    /**
     * Create an instance of {@link FlowDO.StandardReply.SubjectVariables }
     */
    public FlowDO.StandardReply.SubjectVariables createBatchLogicalUnitFlowDOStandardReplySubjectVariables() {
        return new FlowDO.StandardReply.SubjectVariables();
    }

    /**
     * Create an instance of {@link FlowDO.StandardReply.EventReply.ReplyVars.IBVariableDO.SharedIn }
     */
    public FlowDO.StandardReply.EventReply.ReplyVars.IBVariableDO.SharedIn createBatchLogicalUnitFlowDOStandardReplyEventReplyReplyVarsIBVariableDOSharedIn() {
        return new FlowDO.StandardReply.EventReply.ReplyVars.IBVariableDO.SharedIn();
    }

    /**
     * Create an instance of {@link FlowDO.StandardReply.EventReply.ReplyVars.IBVariableDO.ErrorValue.ValueTypeVarInfoDO }
     */
    public FlowDO.StandardReply.EventReply.ReplyVars.IBVariableDO.ErrorValue.ValueTypeVarInfoDO createBatchLogicalUnitFlowDOStandardReplyEventReplyReplyVarsIBVariableDOErrorValueValueTypeVarInfoDO() {
        return new FlowDO.StandardReply.EventReply.ReplyVars.IBVariableDO.ErrorValue.ValueTypeVarInfoDO();
    }

    /**
     * Create an instance of {@link FlowDO.StandardReply.CellNodeData.AncestorLinkNodes }
     */
    public FlowDO.StandardReply.CellNodeData.AncestorLinkNodes createBatchLogicalUnitFlowDOStandardReplyCellNodeDataAncestorLinkNodes() {
        return new FlowDO.StandardReply.CellNodeData.AncestorLinkNodes();
    }

    /**
     * Create an instance of {@link FlowDO.StandardReply.CellNodeData.NodeTags }
     */
    public FlowDO.StandardReply.CellNodeData.NodeTags createBatchLogicalUnitFlowDOStandardReplyCellNodeDataNodeTags() {
        return new FlowDO.StandardReply.CellNodeData.NodeTags();
    }

    /**
     * Create an instance of {@link FlowDO.StandardReply.CellNodeData.SortByList }
     */
    public FlowDO.StandardReply.CellNodeData.SortByList createBatchLogicalUnitFlowDOStandardReplyCellNodeDataSortByList() {
        return new FlowDO.StandardReply.CellNodeData.SortByList();
    }

    /**
     * Create an instance of {@link FlowDO.StandardReply.CellNodeData.Splitters }
     */
    public FlowDO.StandardReply.CellNodeData.Splitters createBatchLogicalUnitFlowDOStandardReplyCellNodeDataSplitters() {
        return new FlowDO.StandardReply.CellNodeData.Splitters();
    }

    /**
     * Create an instance of {@link FlowDO.Schedule.ExecutionOffset }
     */
    public FlowDO.Schedule.ExecutionOffset createBatchLogicalUnitFlowDOScheduleExecutionOffset() {
        return new FlowDO.Schedule.ExecutionOffset();
    }

    /**
     * Create an instance of {@link FlowDO.Schedule.ScheduleActionList }
     */
    public FlowDO.Schedule.ScheduleActionList createBatchLogicalUnitFlowDOScheduleScheduleActionList() {
        return new FlowDO.Schedule.ScheduleActionList();
    }

    /**
     * Create an instance of {@link FlowDO.ConfiguredNotifications.NotificationDO.Events.NotificationEventDO.CcList }
     */
    public FlowDO.ConfiguredNotifications.NotificationDO.Events.NotificationEventDO.CcList createBatchLogicalUnitFlowDOConfiguredNotificationsNotificationDOEventsNotificationEventDOCcList() {
        return new FlowDO.ConfiguredNotifications.NotificationDO.Events.NotificationEventDO.CcList();
    }

    /**
     * Create an instance of {@link FlowDO.ConfiguredNotifications.NotificationDO.Events.NotificationEventDO.SubstitutableSubject }
     */
    public FlowDO.ConfiguredNotifications.NotificationDO.Events.NotificationEventDO.SubstitutableSubject createBatchLogicalUnitFlowDOConfiguredNotificationsNotificationDOEventsNotificationEventDOSubstitutableSubject() {
        return new FlowDO.ConfiguredNotifications.NotificationDO.Events.NotificationEventDO.SubstitutableSubject();
    }

    /**
     * Create an instance of {@link FlowDO.ConfiguredNotifications.NotificationDO.Events.NotificationEventDO.ToList }
     */
    public FlowDO.ConfiguredNotifications.NotificationDO.Events.NotificationEventDO.ToList createBatchLogicalUnitFlowDOConfiguredNotificationsNotificationDOEventsNotificationEventDOToList() {
        return new FlowDO.ConfiguredNotifications.NotificationDO.Events.NotificationEventDO.ToList();
    }

    /**
     * Create an instance of {@link CampaignDO.CampaignExecutionHistoryDO }
     */
    public CampaignDO.CampaignExecutionHistoryDO createBatchLogicalUnitCampaignDOCampaignExecutionHistoryDO() {
        return new CampaignDO.CampaignExecutionHistoryDO();
    }

    /**
     * Create an instance of {@link CampaignDO.CampaignMessages }
     */
    public CampaignDO.CampaignMessages createBatchLogicalUnitCampaignDOCampaignMessages() {
        return new CampaignDO.CampaignMessages();
    }

    /**
     * Create an instance of {@link CampaignDO.CustomPageDetails }
     */
    public CampaignDO.CustomPageDetails createBatchLogicalUnitCampaignDOCustomPageDetails() {
        return new CampaignDO.CustomPageDetails();
    }

    /**
     * Create an instance of {@link CampaignDO.Folder }
     */
    public CampaignDO.Folder createBatchLogicalUnitCampaignDOFolder() {
        return new CampaignDO.Folder();
    }

    /**
     * Create an instance of {@link CampaignDO.ProcessingEndDate }
     */
    public CampaignDO.ProcessingEndDate createBatchLogicalUnitCampaignDOProcessingEndDate() {
        return new CampaignDO.ProcessingEndDate();
    }

    /**
     * Create an instance of {@link CampaignDO.ProcessingStartDate }
     */
    public CampaignDO.ProcessingStartDate createBatchLogicalUnitCampaignDOProcessingStartDate() {
        return new CampaignDO.ProcessingStartDate();
    }

    /**
     * Create an instance of {@link CampaignDO.PublishedObjects }
     */
    public CampaignDO.PublishedObjects createBatchLogicalUnitCampaignDOPublishedObjects() {
        return new CampaignDO.PublishedObjects();
    }

    /**
     * Create an instance of {@link CampaignDO.UserRoles }
     */
    public CampaignDO.UserRoles createBatchLogicalUnitCampaignDOUserRoles() {
        return new CampaignDO.UserRoles();
    }

    /**
     * Create an instance of {@link CampaignDO.VersionHistory.VersionEntries.VersionEntryDO }
     */
    public CampaignDO.VersionHistory.VersionEntries.VersionEntryDO createBatchLogicalUnitCampaignDOVersionHistoryVersionEntriesVersionEntryDO() {
        return new CampaignDO.VersionHistory.VersionEntries.VersionEntryDO();
    }

    /**
     * Create an instance of {@link CampaignDO.Definition.AllPages }
     */
    public CampaignDO.Definition.AllPages createBatchLogicalUnitCampaignDODefinitionAllPages() {
        return new CampaignDO.Definition.AllPages();
    }

    /**
     * Create an instance of {@link CampaignDO.Definition.CustomDetailPages }
     */
    public CampaignDO.Definition.CustomDetailPages createBatchLogicalUnitCampaignDODefinitionCustomDetailPages() {
        return new CampaignDO.Definition.CustomDetailPages();
    }

    /**
     * Create an instance of {@link CampaignDO.Definition.Folder }
     */
    public CampaignDO.Definition.Folder createBatchLogicalUnitCampaignDODefinitionFolder() {
        return new CampaignDO.Definition.Folder();
    }

    /**
     * Create an instance of {@link CampaignDO.Definition.ImportDetails }
     */
    public CampaignDO.Definition.ImportDetails createBatchLogicalUnitCampaignDODefinitionImportDetails() {
        return new CampaignDO.Definition.ImportDetails();
    }

    /**
     * Create an instance of {@link CampaignDO.Definition.StatusList.StatusDO }
     */
    public CampaignDO.Definition.StatusList.StatusDO createBatchLogicalUnitCampaignDODefinitionStatusListStatusDO() {
        return new CampaignDO.Definition.StatusList.StatusDO();
    }

    /**
     * Create an instance of {@link CampaignDO.Definition.SharedIn.SharedDefinitionUseDO }
     */
    public CampaignDO.Definition.SharedIn.SharedDefinitionUseDO createBatchLogicalUnitCampaignDODefinitionSharedInSharedDefinitionUseDO() {
        return new CampaignDO.Definition.SharedIn.SharedDefinitionUseDO();
    }

    /**
     * Create an instance of {@link CampaignDO.Definition.Schedule.ExecutionOffset }
     */
    public CampaignDO.Definition.Schedule.ExecutionOffset createBatchLogicalUnitCampaignDODefinitionScheduleExecutionOffset() {
        return new CampaignDO.Definition.Schedule.ExecutionOffset();
    }

    /**
     * Create an instance of {@link CampaignDO.Definition.Schedule.ScheduleActionList }
     */
    public CampaignDO.Definition.Schedule.ScheduleActionList createBatchLogicalUnitCampaignDODefinitionScheduleScheduleActionList() {
        return new CampaignDO.Definition.Schedule.ScheduleActionList();
    }

    /**
     * Create an instance of {@link CampaignDO.Definition.PageConfigurations.PageConfigDO.ProcessPages.PageDO }
     */
    public CampaignDO.Definition.PageConfigurations.PageConfigDO.ProcessPages.PageDO createBatchLogicalUnitCampaignDODefinitionPageConfigurationsPageConfigDOProcessPagesPageDO() {
        return new CampaignDO.Definition.PageConfigurations.PageConfigDO.ProcessPages.PageDO();
    }

    /**
     * Create an instance of {@link CampaignDO.Definition.PageConfigurations.PageConfigDO.DesignPages.PageDO }
     */
    public CampaignDO.Definition.PageConfigurations.PageConfigDO.DesignPages.PageDO createBatchLogicalUnitCampaignDODefinitionPageConfigurationsPageConfigDODesignPagesPageDO() {
        return new CampaignDO.Definition.PageConfigurations.PageConfigDO.DesignPages.PageDO();
    }

    /**
     * Create an instance of {@link CampaignDO.Definition.CheckListItems.CheckListItemDO }
     */
    public CampaignDO.Definition.CheckListItems.CheckListItemDO createBatchLogicalUnitCampaignDODefinitionCheckListItemsCheckListItemDO() {
        return new CampaignDO.Definition.CheckListItems.CheckListItemDO();
    }

    /**
     * Create an instance of {@link CampaignDO.Definition.CheckList.Steps.CheckListStepDO }
     */
    public CampaignDO.Definition.CheckList.Steps.CheckListStepDO createBatchLogicalUnitCampaignDODefinitionCheckListStepsCheckListStepDO() {
        return new CampaignDO.Definition.CheckList.Steps.CheckListStepDO();
    }

    /**
     * Create an instance of {@link CampaignDO.Definition.BriefData.ChampionChallengerConfigDO }
     */
    public CampaignDO.Definition.BriefData.ChampionChallengerConfigDO createBatchLogicalUnitCampaignDODefinitionBriefDataChampionChallengerConfigDO() {
        return new CampaignDO.Definition.BriefData.ChampionChallengerConfigDO();
    }

    /**
     * Create an instance of {@link CampaignDO.Definition.BriefData.ControlGroupConfigDO }
     */
    public CampaignDO.Definition.BriefData.ControlGroupConfigDO createBatchLogicalUnitCampaignDODefinitionBriefDataControlGroupConfigDO() {
        return new CampaignDO.Definition.BriefData.ControlGroupConfigDO();
    }

    /**
     * Create an instance of {@link CampaignDO.Definition.BriefData.UserDefinedFields }
     */
    public CampaignDO.Definition.BriefData.UserDefinedFields createBatchLogicalUnitCampaignDODefinitionBriefDataUserDefinedFields() {
        return new CampaignDO.Definition.BriefData.UserDefinedFields();
    }

    /**
     * Create an instance of {@link CampaignDO.Definition.Approvers.UserAndGroupDO.Members }
     */
    public CampaignDO.Definition.Approvers.UserAndGroupDO.Members createBatchLogicalUnitCampaignDODefinitionApproversUserAndGroupDOMembers() {
        return new CampaignDO.Definition.Approvers.UserAndGroupDO.Members();
    }

    /**
     * Create an instance of {@link CampaignDO.Definition.AccessControls.UserAndGroupDO.Members }
     */
    public CampaignDO.Definition.AccessControls.UserAndGroupDO.Members createBatchLogicalUnitCampaignDODefinitionAccessControlsUserAndGroupDOMembers() {
        return new CampaignDO.Definition.AccessControls.UserAndGroupDO.Members();
    }

    /**
     * Create an instance of {@link CampaignDO.CheckListItems.CheckListItemDO }
     */
    public CampaignDO.CheckListItems.CheckListItemDO createBatchLogicalUnitCampaignDOCheckListItemsCheckListItemDO() {
        return new CampaignDO.CheckListItems.CheckListItemDO();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProcessNodeDataDO.Process.InputVariableList.IBVariableDO }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link ProcessNodeDataDO.Process.InputVariableList.IBVariableDO }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "IBVariableDO", scope = ProcessNodeDataDO.Process.InputVariableList.class)
    public JAXBElement<ProcessNodeDataDO.Process.InputVariableList.IBVariableDO> createBatchLogicalUnitProcessNodeDataDOProcessInputVariableListIBVariableDO(ProcessNodeDataDO.Process.InputVariableList.IBVariableDO value) {
        return new JAXBElement<ProcessNodeDataDO.Process.InputVariableList.IBVariableDO>(_BatchLogicalUnitProcessNodeDataDOProcessInputVariableListIBVariableDO_QNAME, ProcessNodeDataDO.Process.InputVariableList.IBVariableDO.class, ProcessNodeDataDO.Process.InputVariableList.class, value);
    }

}
