---
name: template-testing
on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
jobs:
  workflows-gradle:
    if: ${{ endsWith(github.repository, 'pipeline-template-java-service') }}
    uses: sas-institute-rnd-internal/workflows-gradle/.github/workflows/base.yaml@v2
    with:
      pipeline: test
      debug: false
      info: true
      cadence-version: latest
      java-version: 17
      artifactory-stack: micro
      run-build: false
      run-test: false
      run-sca-scan: false
      run-sast-scan: false
      pre-publishing: |
        > /dev/null; \
        gomplate --version && \
        \
        find . && \
        sed -i 's/"changeme-team"/"micro-rest"/g' template-data.yaml && \
        sed -i 's/"userid"/"erharb"/g' template-data.yaml && \
        ./template.sh && \
        find . &&
        \
        ./gradlew ${GRADLE_INFO} ${GRADLE_DEBUG} build
      publish-artifacts: true
      publish-artifacts-target: publishToMavenLocal
      build-package: true
      post-packaging: ""
      release-strategy: release-commit
